
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Manage.Model
{

using System;
    using System.Collections.Generic;
    
public partial class V_DataVerifyStep
{

    public string StepName { get; set; }

    public string StepUser { get; set; }

    public string StepAdvice { get; set; }

    public bool StepState { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public long DataKey { get; set; }

}

}
