
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Manage.Model
{

using System;
    using System.Collections.Generic;
    
public partial class V_Role_Menu
{

    public int keyid { get; set; }

    public int RoleId { get; set; }

    public int MenuId { get; set; }

    public string RoleName { get; set; }

    public string MenuName { get; set; }

    public bool C_CanUpdated { get; set; }

    public bool C_CanDelted { get; set; }

    public bool C_CanCreated { get; set; }

    public bool C_CanRead { get; set; }

}

}
