
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Manage.Model
{

using System;
    using System.Collections.Generic;
    
public partial class V_Role_Data_Verify_Step
{

    public int RoleId { get; set; }

    public int ParentId { get; set; }

    public string RoleName { get; set; }

    public string ParentRole { get; set; }

    public string TypeName { get; set; }

    public int VerifyId { get; set; }

    public string VerifyName { get; set; }

    public int stepid { get; set; }

    public string StepName { get; set; }

    public int StepRole { get; set; }

    public string StepRoleName { get; set; }

    public string StepDesction { get; set; }

    public int StepNumber { get; set; }

    public int DataTypeId { get; set; }

}

}
