
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Manage.Model
{

using System;
    using System.Collections.Generic;
    
public partial class V_Verify_Step
{

    public string VerifyName { get; set; }

    public string StepName { get; set; }

    public string StepDescription { get; set; }

    public int StepNumber { get; set; }

    public int StepRole { get; set; }

    public int VerifyId { get; set; }

    public int StepId { get; set; }

}

}
